
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 4-JHarvey
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        ImageIcon Logo = new ImageIcon("NEA Logo.png");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignOut = new javax.swing.JButton();
        CreateTournament = new javax.swing.JButton();
        LoadTournament = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignOut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SignOut.setText("Sign out");
        SignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutActionPerformed(evt);
            }
        });
        getContentPane().add(SignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 200, 70));

        CreateTournament.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CreateTournament.setText("Create Tournament");
        CreateTournament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateTournamentActionPerformed(evt);
            }
        });
        getContentPane().add(CreateTournament, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 490, 90));

        LoadTournament.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LoadTournament.setText("Load Tournament");
        LoadTournament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadTournamentActionPerformed(evt);
            }
        });
        getContentPane().add(LoadTournament, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 490, 90));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("WELCOME TO EMS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 230, 130));
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, 120, 130));

        setBounds(0, 0, 1876, 864);
    }// </editor-fold>//GEN-END:initComponents

    private void LoadTournamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadTournamentActionPerformed
        //sends to load tournament screen
        LoadTournament History = new LoadTournament();
        this.dispose();
        History.setVisible(true);
    }//GEN-LAST:event_LoadTournamentActionPerformed

    private void SignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutActionPerformed
        //logs them out to login screen
        LogInScreen LogIn = new LogInScreen();
        this.dispose();
        LogIn.setVisible(true);
    }//GEN-LAST:event_SignOutActionPerformed

    private void CreateTournamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateTournamentActionPerformed
        //sends them to create tournament screen
        CreateTournament Tournament = new CreateTournament();
        this.dispose();
        Tournament.setVisible(true);
    }//GEN-LAST:event_CreateTournamentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateTournament;
    private javax.swing.JButton LoadTournament;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton SignOut;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
