import java.awt.*;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 4-JHarvey
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    private JPanel playerReg = new JPanel();
    private int tournamentID;
    
    public Registration(int tournamentID) {
        this.tournamentID = tournamentID;
        initComponents();
        //JFrame fills the screen
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        //Adds the additional player boxes to the JFrame
        playerReg.setLayout(new BoxLayout(playerReg, BoxLayout.Y_AXIS));
        getContentPane().add(playerReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 340, 300));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SchoolName = new javax.swing.JTextField();
        Username = new javax.swing.JTextField();
        NumOfPlayers = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Register = new javax.swing.JButton();

        jPanel1.add(jPanel3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("School name (optional)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Team name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Number of players");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 170, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Contact Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, 50));

        SchoolName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchoolNameActionPerformed(evt);
            }
        });
        getContentPane().add(SchoolName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 410, 70));

        Username.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                UsernameAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 340, 70));

        NumOfPlayers.setText("Press Enter once after inputting number");
        NumOfPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumOfPlayersActionPerformed(evt);
            }
        });
        getContentPane().add(NumOfPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 340, 70));
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 430, 70));

        Register.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 310, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SchoolNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchoolNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SchoolNameActionPerformed

    private void UsernameAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_UsernameAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameAncestorMoved

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        //Gets the Team Data from the registration form
        String Name = Username.getText();
        String PlayerAmount = NumOfPlayers.getText();
        String Mail = Email.getText();
        
        
        //makes sure that all required data is entered before continueing to next screen
        if(Name.equals("") || PlayerAmount.equals("") || Mail.equals("")){
            
               JOptionPane.showMessageDialog(null,"Please fill in the required parts of the form");
        }
        else{
            CompletionScreen Completion = new CompletionScreen(tournamentID);
            this.dispose();
            Completion.setVisible(true);
        }
        
       
        // inserts the Team Data into the database
        try(Connection connect = DatabaseConnection.getConnection()){
            String sql = "INSERT INTO Team(TeamName, email, TournamentID) VALUES (?, ?, ?)";
            PreparedStatement ps = connect.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            ps.setString(1, Name);
            ps.setString(2, Mail);
            ps.setInt(3, tournamentID);
            ps.executeUpdate();
            
            System.out.println("Inserting team with tournamentID = " + tournamentID);
            
            ResultSet rs = ps.getGeneratedKeys();
            
            //sets up Team IDs
            int teamID = 0;
            if(rs.next()){
                teamID = rs.getInt(1);
            }
            
            //Checks all player boxes for user names and inserts ir inro the database
            for (Component player : playerReg.getComponents()){
                if(player instanceof JTextField){
                    JTextField text = (JTextField) player;
                    String UserName = text.getText();
                    if(!UserName.isEmpty()){
                         String playerQuery = "INSERT INTO Player(Username, TeamID) VALUES (?, ?)";
                         PreparedStatement psPlayer = connect.prepareStatement(playerQuery);
                         psPlayer.setString(1, UserName);
                         psPlayer.setInt(2, teamID);
                         psPlayer.executeUpdate();
                    }
                }
            }
                        
            // prints any errors that occur either SQL or Java side
        }   catch (SQLException ex) {       
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "SQL error " + ex.getMessage());
        }  catch (Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Unexpected error " + ex.toString());
        }
                  
    }//GEN-LAST:event_RegisterActionPerformed

    private void NumOfPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumOfPlayersActionPerformed
        playerReg.removeAll();
        
        int Players = 0;
        //this gets the number inputted into this box
        try{
            Players = Integer.parseInt(NumOfPlayers.getText());
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "please enter valid number");
        }
        // creates additionalboxes to input Username into
        for(int i = 0; i < Players; i++){
            JTextField player = new JTextField ();
            player.setName("Player" + i);
            player.setBorder(javax.swing.BorderFactory.createTitledBorder("Player" + i));
            playerReg.add(player);
        }
        
        playerReg.revalidate();
        playerReg.repaint();
    }//GEN-LAST:event_NumOfPlayersActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JTextField NumOfPlayers;
    private javax.swing.JButton Register;
    private javax.swing.JTextField SchoolName;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
